<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="latin1" />
    <title>erl_error (erl_interface) -  - erldocs.com (Erlang Documentation)</title>
    <link rel="search" type="application/opensearchdescription+xml"
          title="erldocs" href="/search.xml">
    <link type="text/css" rel="stylesheet" href="../erldocs.css" />
  </head>
  <body>

    <div id="sidebar" class="inactive">
      <input type="text" id="search" autocomplete="off"
             placeholder="press TAB to search" />
      <ul id="results"> </ul>
    </div>

    <div id="content">
      <div style="margin:0px; padding:10px 20px;">
        
  
  <h1>erl_error</h1>
  <libsummary>Error Print Routines</libsummary>
  <div class="description">
    <p>This module contains some error printing routines taken
      from <em>Advanced Programming in the UNIX Environment</em> 
      by W. Richard Stevens. </p>
    <p>These functions are all called in the same manner as
      <code>printf()</code>, i.e. with a string containing format specifiers
      followed by a list of corresponding arguments. All output from
      these functions is to <code>stderr</code>.</p>
  </div>
  <div class="functions"><h4>Functions</h4><hr  />
    <div class="function">
      <pre>void erl_err_msg(FormatStr, ... )</pre>
      
      <ul class="type">
        <li><code>const char *FormatStr;</code></li>
      </ul>
      <div class="description">
        <p>The message provided by the caller is printed. This
          function is simply a wrapper for <code>fprintf()</code>.</p>
      </div>
    </div>
    <div class="function">
      <pre>void erl_err_quit(FormatStr, ... )</pre>
      
      <ul class="type">
        <li><code>const char *FormatStr;</code></li>
      </ul>
      <div class="description">
        <p>Use this function when a fatal error has occurred that
          is not due to a system call. The message provided by the
          caller is printed and the process terminates with an exit
          value of 1. The function does not return.</p>
      </div>
    </div>
    <div class="function">
      <pre>void erl_err_ret(FormatStr, ... )</pre>
      
      <ul class="type">
        <li><code>const char *FormatStr;</code></li>
      </ul>
      <div class="description">
        <p>Use this function after a failed system call. The message
          provided by the caller is printed followed by a string
          describing the reason for failure. </p>
      </div>
    </div>
    <div class="function">
      <pre>void erl_err_sys(FormatStr, ... )</pre>
      
      <ul class="type">
        <li><code>const char *FormatStr;</code></li>
      </ul>
      <div class="description">
        <p>Use this function after a failed system call. The message
          provided by the caller is printed followed by a string
          describing the reason for failure, and the process
          terminates with an exit value of 1. The function does not
          return.</p>
      </div>
    </div>
  </div>

  <div class="section">
    <h4>Error Reporting</h4>
    <p>Most functions in erl_interface report failures to the caller by
      returning some otherwise meaningless value (typically <code>NULL</code>
      or a negative number). As this only tells you that things did not
      go well, you will have to examine the error code in
      <code>erl_errno</code> if you want to find out more about the failure.</p>
  </div>
  <div class="functions"><h4>Functions</h4><hr  />
    <div class="function">
      <pre>volatile int erl_errno</pre>
      
      <div class="description">
        <p><code>erl_errno</code> is initially (at program startup) zero and
          is then set by many erl_interface functions on failure to a
          non-zero error code to indicate what kind of error it
          encountered. A successful function call might change
          <code>erl_errno</code> (by calling some other function that
          fails), but no function will ever set it to zero. This means
          that you cannot use <code>erl_errno</code> to see <em>if</em> a
          function call failed. Instead, each function reports failure
          in its own way (usually by returning a negative number or
          <code>NULL</code>), in which case you can examine <code>erl_errno</code>
          for details.</p>
        <p><code>erl_errno</code> uses the error codes defined in your
          system's <code>&lt;errno.h&gt;</code>.</p>
        <div class="note"><h2>Note!</h2>
          <p>Actually, <code>erl_errno</code> is a "modifiable lvalue" (just
            like ISO C defines <code>errno</code> to be) rather than a
            variable. This means it might be implemented as a macro
            (expanding to, e.g., <code>*_erl_errno()</code>). For reasons of
            thread- (or task-)safety, this is exactly what we do on most
            platforms.</p>
        </div>
      </div>
    </div>
  </div>

      </div>
      <div id="funwrapper">
        <a id="viewfuns">View Functions</a>
        <ul id="funs" />
      </div>
    </div>

    <script type="text/javascript">
      var CURRENT_ROOT = "../";
    </script>

    <script type="text/javascript" src="../jquery.js"></script>
    <script type="text/javascript" src="../erldocs_index.js"></script>
    <script type="text/javascript" src="../erldocs.js"></script>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-59760-14']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script');
        ga.src = ('https:' == document.location.protocol ?
          'https://ssl' : 'http://www') +
          '.google-analytics.com/ga.js';
        ga.setAttribute('async', 'true');
        document.documentElement.firstChild.appendChild(ga);
      })();
    </script>
  </body>
</html>

